"""Legacy PDF generator for the /api/v1/analyze complexity report.

Kept import-stable for the v1 endpoint; new work lands in
src/projects/pdf.py (the runbook PDF). Both use ReportLab Platypus.
"""

from __future__ import annotations

import io
from typing import Any

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


class PDFReportGenerator:
    """Render a ComplexityReport as a 1-2 page PDF."""

    def generate(self, report: Any) -> bytes:
        """Return PDF bytes for the given ComplexityReport-shaped object."""
        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf,
            pagesize=LETTER,
            leftMargin=0.75 * inch,
            rightMargin=0.75 * inch,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
            title="Depart Complexity Analysis",
            author="Depart",
        )
        doc.build(list(self._story(report)))
        return buf.getvalue()

    # ─── story ───────────────────────────────────────────────────────────────

    def _story(self, report: Any):
        styles = self._styles()

        yield Paragraph("Oracle → PostgreSQL Complexity Analysis", styles["Title"])
        yield Spacer(1, 0.2 * inch)
        yield HRFlowable(width="100%", thickness=0.5)
        yield Spacer(1, 0.1 * inch)

        yield Paragraph(
            f"<b>Complexity score:</b> {report.score} / 100",
            styles["Body"],
        )
        yield Paragraph(
            f"<b>Total lines:</b> {report.total_lines:,}",
            styles["Body"],
        )
        yield Paragraph(
            f"<b>Effort estimate:</b> {report.effort_estimate_days} engineer-days "
            f"&nbsp;&nbsp;|&nbsp;&nbsp; <b>Cost:</b> ${int(report.estimated_cost):,}",
            styles["Body"],
        )
        yield Spacer(1, 0.2 * inch)

        # Tier breakdown table.
        data = [
            ["Tier", "Lines", "Description"],
            [
                "A — auto-convertible",
                f"{report.auto_convertible_lines:,}",
                "Deterministic conversion, no manual review",
            ],
            [
                "B — needs review",
                f"{report.needs_review_lines:,}",
                "Mechanical rewrite (CONNECT BY, MERGE, ROWNUM, ...)",
            ],
            [
                "C — must rewrite",
                f"{report.must_rewrite_lines:,}",
                "Architectural change (autonomous tx, AQ, scheduler, ...)",
            ],
        ]
        t = Table(data, colWidths=[2 * inch, 1.2 * inch, 3.3 * inch])
        t.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), HexColor("#E0E0E0")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("ALIGN", (1, 0), (1, -1), "RIGHT"),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("GRID", (0, 0), (-1, -1), 0.25, HexColor("#9E9E9E")),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ]
            )
        )
        yield t
        yield Spacer(1, 0.3 * inch)

        # Top constructs to address first.
        if getattr(report, "top_10_constructs", None):
            yield Paragraph("Top constructs to address", styles["H2"])
            yield Spacer(1, 0.05 * inch)
            for c in report.top_10_constructs[:10]:
                yield Paragraph(f"• {c}", styles["BodySmall"])
            yield Spacer(1, 0.2 * inch)

        # Tier-C detail (the items that drive cost).
        if getattr(report, "tier_c_constructs", None):
            yield Paragraph("Tier-C constructs (require architectural attention)", styles["H2"])
            for c in sorted(set(report.tier_c_constructs)):
                yield Paragraph(f"• {c}", styles["BodySmall"])
            yield Spacer(1, 0.2 * inch)

        if getattr(report, "tier_b_constructs", None):
            yield Paragraph("Tier-B constructs (mechanical rewrite)", styles["H2"])
            for c in sorted(set(report.tier_b_constructs)):
                yield Paragraph(f"• {c}", styles["BodySmall"])
            yield Spacer(1, 0.2 * inch)

        yield Paragraph(
            "Generated by Depart — Oracle → PostgreSQL migration platform.",
            styles["Footnote"],
        )

    @staticmethod
    def _styles():
        base = getSampleStyleSheet()
        return {
            "Title": ParagraphStyle(
                "Title",
                parent=base["Title"],
                fontSize=20,
                textColor=HexColor("#212121"),
                spaceAfter=10,
            ),
            "H2": ParagraphStyle(
                "H2",
                parent=base["Heading2"],
                fontSize=12,
                textColor=HexColor("#1565C0"),
                spaceBefore=8,
                spaceAfter=4,
            ),
            "Body": ParagraphStyle(
                "Body",
                parent=base["BodyText"],
                fontSize=10,
                leading=14,
            ),
            "BodySmall": ParagraphStyle(
                "BodySmall",
                parent=base["BodyText"],
                fontSize=9,
                leading=12,
                leftIndent=12,
            ),
            "Footnote": ParagraphStyle(
                "Footnote",
                parent=base["BodyText"],
                fontSize=8,
                leading=10,
                textColor=HexColor("#616161"),
            ),
        }
