#!/usr/bin/env python3
"""Generate the ANTLR PL/SQL parser into src/source/oracle/_generated/.

Caches antlr-4.13.2-complete.jar under ~/.cache/depart-grammar/. Requires a
Java runtime on PATH (the antlr tool is a JAR). On Mac: `brew install
temurin`. On Debian/Ubuntu: `apt install default-jre-headless`.

This script is the single entry point for grammar codegen. The Makefile,
Dockerfile, and CI all call it — there is no other path to producing the
generated files.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import urllib.request
from pathlib import Path

ANTLR_VERSION = "4.13.2"
ANTLR_JAR_URL = f"https://www.antlr.org/download/antlr-{ANTLR_VERSION}-complete.jar"
CACHE_DIR = Path.home() / ".cache" / "depart-grammar"
JAR_PATH = CACHE_DIR / f"antlr-{ANTLR_VERSION}-complete.jar"

API_ROOT = Path(__file__).resolve().parents[1]
GRAMMAR_DIR = API_ROOT / "src" / "source" / "oracle" / "grammar"
OUT_DIR = API_ROOT / "src" / "source" / "oracle" / "_generated"


def ensure_jar() -> Path:
    if JAR_PATH.exists():
        return JAR_PATH
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Downloading {ANTLR_JAR_URL} -> {JAR_PATH}", file=sys.stderr)
    urllib.request.urlretrieve(ANTLR_JAR_URL, JAR_PATH)
    return JAR_PATH


def ensure_java() -> str:
    java = shutil.which("java")
    if not java:
        sys.exit(
            "java not found on PATH. Install a JRE: "
            "`brew install temurin` (macOS) or `apt install default-jre-headless` (Debian)."
        )
    return java


def generate(force: bool = False) -> int:
    grammars = sorted(GRAMMAR_DIR.glob("*.g4"))
    if not grammars:
        sys.exit(f"No .g4 files found under {GRAMMAR_DIR}")

    if OUT_DIR.exists() and not force:
        # Skip if output is newer than every grammar — cheap incremental.
        out_mtime = max((p.stat().st_mtime for p in OUT_DIR.rglob("*.py")), default=0)
        src_mtime = max(p.stat().st_mtime for p in grammars)
        if out_mtime >= src_mtime:
            print(f"Up-to-date: {OUT_DIR}", file=sys.stderr)
            return 0

    java = ensure_java()
    jar = ensure_jar()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    # Marker so callers know the package is meant to be import-safe.
    (OUT_DIR / "__init__.py").write_text(
        '"""Generated by scripts/generate_grammar.py from src/source/oracle/grammar/.\n'
        'Do not edit by hand. Regenerate with `make grammar`."""\n'
    )

    cmd = [
        java, "-jar", str(jar),
        "-Dlanguage=Python3",
        "-visitor",
        "-o", str(OUT_DIR),
        "-Xexact-output-dir",
        *[str(p) for p in grammars],
    ]
    print(" ".join(cmd), file=sys.stderr)
    result = subprocess.run(cmd, cwd=GRAMMAR_DIR)
    if result.returncode != 0:
        return result.returncode

    # The PL/SQL grammar references hand-written base classes
    # (PlSqlLexerBase, PlSqlParserBase) that contain semantic predicates and
    # version flags. ANTLR doesn't generate them — they must be co-located
    # with the generated Python so `from .PlSqlLexerBase import ...` resolves.
    # We also patch the upstream's absolute `from PlSqlLexer import ...` to
    # the relative form required by Python package imports.
    for base_name in ("PlSqlLexerBase.py", "PlSqlParserBase.py"):
        src_path = GRAMMAR_DIR / base_name
        if not src_path.exists():
            sys.exit(f"Missing required base class file: {src_path}")
        text = src_path.read_text()
        # Upstream uses non-package imports; fix them in place during copy.
        text = text.replace("from PlSqlLexer import", "from .PlSqlLexer import")
        text = text.replace("from PlSqlParser import", "from .PlSqlParser import")
        (OUT_DIR / base_name).write_text(text)

    # The upstream antlr/grammars-v4 PL/SQL grammar embeds JavaScript-style
    # `this.foo()` references inside semantic-predicate action blocks (e.g.
    # `this.IsNewlineAtPos(-4)`, `this.isVersion12()`). ANTLR's Python target
    # copies those tokens verbatim, so the generated lexer/parser raise
    # NameError as soon as a predicate fires. Rewrite them to `self.` after
    # codegen — this matches what the upstream Java/JS consumers see.
    for gen_file in ("PlSqlLexer.py", "PlSqlParser.py"):
        path = OUT_DIR / gen_file
        if path.exists():
            content = path.read_text()
            # Word-boundary replace so we don't touch e.g. `this_thing`.
            import re
            patched = re.sub(r"\bthis\.", "self.", content)
            if patched != content:
                path.write_text(patched)

    print(f"Generated -> {OUT_DIR}", file=sys.stderr)
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--force", action="store_true", help="Regenerate even if up-to-date")
    args = p.parse_args()
    return generate(force=args.force)


if __name__ == "__main__":
    sys.exit(main())
